name: thesis_gutmann
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=20.2.4
  - pip:
    - numpy==1.19.5
    - matplotlib==3.4.2
    - pandas==1.1.4
    - jpype1==1.2.1
    - git+https://github.com/quaquel/pyNetLogo.git@89ff90eaf1c2ebac5db40f8682d56177dcbd9513 #pyNetLogo
    - cmcrameri==1.2
    - Tensorforce==0.6.3
    - hpbandster==0.7.4